services:
    andreask.forum_overview.controller:
        class: andreask\forum_overview\controller\main_controller
        arguments:
            - '@dbal.conn'
            - '@template'
            - '@auth'
            - '@request'
            - '@controller.helper'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
    andreas.forum_overview.classes.get_info:
        class: andreask\forum_overview\classes\get_info
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@log'
            - '@service_container'
